apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: webapp-depl
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webapp-depl
      spec:
        template:
          spec:
            containers:
              - name: webapp
                image: cpaschalidi/webapp
                env:
                  - name: NEXT_PUBLIC_API_URL
                    value: 'https://localhost'
