apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: auth-redis-depl
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-redis-depl
      spec:
        replicas: 1
        strategy:
          rollingUpdate:
            maxUnavailable: 0
